String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Epic Fortnite Gamer Clan</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>change.</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://wf910.github.io\">http://wf910.github.io</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Pro Fortnite Gang",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-Fortnite Battle Royal #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Galaxy Skin',
    '%4'                    : 'Brilliant Bomber',
    '%8'                    : 'Glow Skin',
    '%16'                   : 'Aerial Assault Trooper',
    '%32'                   : 'Gold Peely',
    '%64'                   : 'Renegade Raider',
    '%128'                  : 'Purple Skull Trooper',
    '%256'                  : 'Ghoul Trooper',
    '%512'                  : 'Giddy Up',
    '%1024'                 : 'Jonesy',
    '%2048'                 : 'Kyrie Irving',
    '%4096'                 : 'Merry Marauder',
    '%8192'                 : 'LeBron James',
    '%p0'                   : 'Galaxy Skin',
    '%p4'                   : 'Brilliant Bomber',
    '%p8'                   : 'Glow Skin',
    '%p16'                  : 'Aerial Assault Trooper',
    '%p32'                  : 'Gold Peely',
    '%p64'                  : 'Renegade Raider',
    '%p128'                 : 'Purple Skull Trooper',
    '%p256'                 : 'Ghoul Trooper',
    '%p512'                 : 'Giddy Up',
    '%p1024'                : 'Jonesy',
    '%p2048'                : 'Kyrie Irving',
    '%p4096'                : 'Merry Marauder',
    '%p8192'                : 'LeBron James'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048 Fortnite #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Galaxy Skin',
    '%4'                    : 'Brilliant Bomber',
    '%8'                    : 'Glow Skin',
    '%16'                   : 'Aerial Assault Trooper',
    '%32'                   : 'Gold Peely',
    '%64'                   : 'Renegade Raider',
    '%128'                  : 'Purple Skull Trooper',
    '%256'                  : 'Ghoul Trooper',
    '%512'                  : 'Giddy Up',
    '%1024'                 : 'Jonesy',
    '%2048'                 : 'Kyrie Irving',
    '%4096'                 : 'Merry Marauder',
    '%8192'                 : 'LeBron James',
    '%p0'                   : 'Galaxy Skin',
    '%p4'                   : 'Brilliant Bomber',
    '%p8'                   : 'Glow Skin',
    '%p16'                  : 'Aerial Assault Trooper',
    '%p32'                  : 'Gold Peely',
    '%p64'                  : 'Renegade Raider',
    '%p128'                 : 'Purple Skull Trooper',
    '%p256'                 : 'Skull Ranger',
    '%p512'                 : 'Giddy Up',
    '%p1024'                : 'Jonesy',
    '%p2048'                : 'Kyrie Irving',
    '%p4096'                : 'Merry Marauder',
    '%p8192'                : 'LeBron James'
  }

});
